<?php

return [
    "creator-inputs" => [
        [
            "type" => "text",
            "name" => "name",
            "icon" => "far fa-user",
            "dir" => "rtl",
            "maxlength" => "50",
            "class" => "form-control inputTextCreator",
            "id" => "name_creator_id",
            "placeholder" => "اسم المستخدم",
            "defer" => true,
            "lable" => "اسم المستخدم",
            "validation" => "text-danger reset-validation name-validation",
            "disabled" => false,
            "value" => "",
        ],
        [
            "type" => "email",
            "name" => "email",
            "icon" => "fas fa-at",
            "dir" => "ltr",
            "maxlength" => "50",
            "class" => "form-control inputTextCreator",
            "id" => "email_creator_id",
            "placeholder" => "البريد الالكتروني",
            "defer" => true,
            "lable" => "البريد الالكتروني",
            "validation" => "text-danger reset-validation email-validation",
            "disabled" => false,
            "value" => "",
        ],
        [
            "type" => "password",
            "name" => "password",
            "icon" => "fas fa-key",
            "dir" => "ltr",
            "maxlength" => "50",
            "class" => "form-control inputTextCreator",
            "id" => "password_creator_id",
            "placeholder" => "كلمة السر",
            "defer" => true,
            "lable" => "كلمة السر",
            "validation" => "text-danger reset-validation password-validation",
            "disabled" => false,
            "value" => "",
        ],
        [
            "type" => "text",
            "name" => "phone",
            "icon" => "fas fa-phone",
            "dir" => "ltr",
            "maxlength" => "10",
            "class" => "form-control inputTextCreator",
            "id" => "phone_creator_id",
            "placeholder" => "رقم الجوال",
            "defer" => true,
            "lable" => "رقم الجوال",
            "validation" => "text-danger reset-validation phone-validation",
            "disabled" => false,
            "value" => "",
        ]
    ],
];
